---
Parameters:
  UserInputForSecuiryGroupName:
    Description: Security Group Description
    Type: String
    
  Resources:
    MyInstance:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-west-2a
        ImageId: ami-07c900643d183b180
        InstanceType: t2.micro
        SecurityGroups:
          - !Ref SSHSecurityGroup
          - !Ref ServerSecuirtyGroup
        
    MyEIP:
      Type: AWS::EC2::EIP
      Properties:
        InstanceId: !Ref MyInstance

    SSHSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable SSH via port 22
        SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
    
    ServerSecuirtyGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: !Ref UserInputForSecuiryGroupName
        SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        - CidrIp: 192.168.1.1/32
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
