---
Resources:
    MyInstance:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: us-west-2a
            ImageId: ami-07c900643d183b180
            InstanceType: t2.micro