AWSTemplateFormatVersion: "2010-09-09"
Mappings:
  RegionMaps:
    us-east-1:
      "32": "ami-6411e20d"
      "64": "ami-7a11e213"
    us-west-1:
      "32": "ami-c9c7978c"
      "64": "ami-cfc7978a"
    us-west-2:
      "32": "ami-07c900643d183b180"
      "64": "ami-07c900643d183b180"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMaps, !Ref "AWS::Region", 32]
      InstanceType: t2.micro
